# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_checksum'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checksum',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
