# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_checksum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='checksum',
            field=models.CharField(default='', max_length=32),
        ),
    ]
