# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20170212_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ref',
            field=models.IntegerField(default=-1),
        ),
    ]
