# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20170212_1656'),
        ('payments', '0005_payment_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.Game'),
            preserve_default=False,
        ),
    ]
