# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 09:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('url', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('description', models.CharField(max_length=255)),
                ('ratingsum', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('ACTION', 'Action'), ('ADVENTURE', 'Adventure'), ('ARCADE', 'Arcade'), ('BOARD', 'Board')], max_length=12)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', related_query_name='game', to=settings.AUTH_USER_MODEL)),
                ('raters', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
