# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-11 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20170211_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('ACTION', 'Action'), ('ADVENTURE', 'Adventure'), ('ARCADE', 'Arcade'), ('BOARD', 'Board'), ('DRIVING', 'Driving'), ('STRATEGY', 'Strategy'), ('HORROR', 'Horror')], max_length=12),
        ),
    ]
