# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20170211_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinventory',
            name='games',
            field=models.ManyToManyField(related_name='inventories', to='store.Game'),
        ),
    ]
